FROM --platform=linux/amd64 python:3.10-slim

WORKDIR /app

# Copy source files
COPY . .

# Create required folders
RUN mkdir -p input output

# Install system dependencies for fitz if needed
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
 && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command
CMD ["python", "main.py"]
